-- Tags, estimativa de tempo e prazo com hora
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "tagIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "estimateMin" INTEGER;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "dueHasTime" BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS "Tag" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "color" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Tag_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "Tag_name_key" ON "Tag"("name");
